
name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - provision_azure_function #temporary, change to master after

env:
  AZURE_FUNCTIONAPP_NAME: shelterapp-scrapers # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.8'                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-n-test-n-deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master 
      
    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Set environmental variables'
      run: |
        echo 'python version'
        echo ${{ env.PYTHON_VERSION }}
        export DBUSERNAME= /some/secret
        #export DBUSERNAME= ${{ secrets.DBUSERNAME }}
        #export PW= ${{ secrets.DBUSERNAME }}
        echo $DBUSERNAME
        #echo $PW

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.1.8
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_NEW }}
